# Generated by Django 4.2.5 on 2023-09-18 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postgre_app', '0003_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='RollNumber',
            new_name='rollnumber',
        ),
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.CharField(default=None, max_length=255, primary_key='True', serialize=False),
        ),
    ]
